ALTER TABLE agent DROP COLUMN IF EXISTS is_global;
ALTER TABLE skill DROP COLUMN IF EXISTS is_global;
ALTER TABLE quick_action DROP COLUMN IF EXISTS is_global;
ALTER TABLE squad DROP COLUMN IF EXISTS is_global;
